@host = {{be-auth-url}}/auth

###

POST {{host}}/login
Content-Type: application/json

{
  "username": "test",
  "password": "",
  "account": ""
}

###

GET {{host}}/error
Content-Type: application/json