@host = {{be-auth-url}}/auth

###

POST {{host}}/login
Content-Type: application/json

{
  "username": "test",
  "password": "test",
  "account": "test"
}

###

GET {{host}}/error
Content-Type: application/json
Authorization: {{jwToken}}

###

POST {{host}}/register
Content-Type: application/json

{
  "userName": "test",
  "password": "test",
  "account": "test"
}

###

POST {{host}}/logout
Content-Type: application/json
//Authorization: {{jwToken}}