@host = {{be-auth-url}}/auth

###

POST {{host}}/login
Content-Type: application/json

{
  "username": "test",
  "password": "test",
  "account": "aaa"
}

###

GET {{host}}/error
Content-Type: application/json

###

POST {{host}}/register
Content-Type: application/json

{
  "username": "test",
  "password": "test",
  "account": "123"
}